"use client"

import { useState } from "react"
import { Bell, Check, ChevronDown, Database, KeyRound, LockKeyhole, Save, ShieldCheck, Store, UserRound, Webhook, Zap } from "lucide-react"
import { LoadingDots } from "@/components/ui/loading"
import { StatusDot } from "@/components/ui/status"

const navItems = ["Workspace", "Profile", "Orders", "Notifications", "Security", "Integrations"]

export function SettingsWorkspace() {
  const [activeSection, setActiveSection] = useState("Workspace")
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [emailUpdates, setEmailUpdates] = useState(true)
  const [lowStockAlerts, setLowStockAlerts] = useState(true)

  const saveSettings = () => {
    setSaving(true)
    setSaved(false)
    window.setTimeout(() => {
      setSaving(false)
      setSaved(true)
      window.setTimeout(() => setSaved(false), 2400)
    }, 900)
  }

  return <main className="flex-1 p-6 lg:p-10"><div className="mx-auto max-w-6xl">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="eyebrow flex items-center gap-2"><span>Orderly OMS</span><span>/</span><span className="text-neutral-800">Administration</span></div><h1 className="mt-4 text-4xl font-semibold tracking-[-.06em] sm:text-5xl">Settings</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">Manage your workspace, operational rules, notifications, and connected services.</p></div><button className="button-primary h-11 px-5" onClick={saveSettings} disabled={saving}>{saving ? <LoadingDots /> : saved ? <><Check size={16} /> Saved</> : <><Save size={16} /> Save changes</>}</button></div>

    <div className="mt-10 grid gap-6 lg:grid-cols-[220px_1fr]">
      <nav className="h-fit rounded-3xl bg-white p-2 shadow-[0_12px_40px_rgba(28,27,27,.05)]" aria-label="Settings sections">{navItems.map((item) => <button key={item} onClick={() => setActiveSection(item)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm transition ${activeSection === item ? "bg-black text-white" : "text-neutral-500 hover:bg-[#f7f3f2] hover:text-neutral-900"}`}><span className={`grid size-7 place-items-center rounded-lg ${activeSection === item ? "bg-white/15" : "bg-[#f7f3f2]"}`}><SectionIcon item={item} /></span>{item}</button>)}</nav>

      <div className="space-y-6">
        {activeSection === "Workspace" && <><SettingsCard icon={<Store size={18} />} eyebrow="Workspace identity" title="General settings" description="The details your team uses to identify this operation."><div className="grid gap-5 sm:grid-cols-2"><Field label="Workspace name" value="Orderly HQ" /><Field label="Workspace slug" value="orderly-hq" suffix="orderly.app/" /><SelectField label="Default timezone" value="America/New_York" options={["America/New_York", "America/Los_Angeles", "Europe/London"]} /><SelectField label="Default currency" value="USD — US Dollar" options={["USD — US Dollar", "EUR — Euro", "GBP — Pound Sterling"]} /></div></SettingsCard><SettingsCard icon={<Zap size={18} />} eyebrow="Operations" title="Order defaults" description="Set the defaults applied to new orders and fulfillment workflows."><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Default order status" value="Pending review" options={["Pending review", "Pending", "Completed"]} /><SelectField label="Default fulfillment method" value="Standard shipping" options={["Standard shipping", "Express shipping", "Local pickup"]} /><ToggleRow label="Require order review" description="Hold new orders until an admin approves them." enabled={true} /><ToggleRow label="Allow partial fulfillment" description="Let teams ship available items separately." enabled={false} /></div></SettingsCard></>}
        {activeSection === "Profile" && <SettingsCard icon={<UserRound size={18} />} eyebrow="Your account" title="Administrator profile" description="Update the profile details shown to your workspace team."><div className="flex items-center gap-4 rounded-2xl bg-[#f7f3f2] p-4"><div className="grid size-14 place-items-center rounded-full bg-black text-sm font-semibold text-white">AM</div><div><p className="font-medium">Alex Morgan</p><p className="text-sm text-neutral-500">Administrator · alex@orderly.app</p></div><button className="button-secondary ml-auto h-9 px-3 text-xs">Change photo</button></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Full name" value="Alex Morgan" /><Field label="Email address" value="alex@orderly.app" /><Field label="Role" value="Administrator" disabled /><Field label="Phone number" value="+1 (555) 014-2890" /></div></SettingsCard>}
        {activeSection === "Orders" && <SettingsCard icon={<Store size={18} />} eyebrow="Order management" title="Order policies" description="Control how orders are processed across the platform."><div className="space-y-1"><ToggleRow label="Auto-confirm paid orders" description="Move paid orders directly into Pending." enabled={true} /><ToggleRow label="Notify customers on status changes" description="Send an email when an order status changes." enabled={emailUpdates} onChange={() => setEmailUpdates(!emailUpdates)} /><ToggleRow label="Enable fraud review queue" description="Flag unusual orders for manual inspection." enabled={true} /><ToggleRow label="Allow customer cancellations" description="Customers can request cancellation before fulfillment." enabled={false} /></div></SettingsCard>}
        {activeSection === "Notifications" && <SettingsCard icon={<Bell size={18} />} eyebrow="Communication" title="Notification preferences" description="Choose which events should reach your team."><div className="space-y-1"><ToggleRow label="Email activity updates" description="Receive a daily summary of orders and revenue." enabled={emailUpdates} onChange={() => setEmailUpdates(!emailUpdates)} /><ToggleRow label="Low stock alerts" description="Notify admins when inventory falls below its threshold." enabled={lowStockAlerts} onChange={() => setLowStockAlerts(!lowStockAlerts)} /><ToggleRow label="System incidents" description="Always notify admins about service interruptions." enabled={true} locked /><ToggleRow label="Weekly performance digest" description="Get a Monday summary of operational performance." enabled={false} /></div></SettingsCard>}
        {activeSection === "Security" && <><SettingsCard icon={<ShieldCheck size={18} />} eyebrow="Access control" title="Security & access" description="Keep your workspace and operational data protected."><div className="space-y-1"><ActionRow icon={<KeyRound size={17} />} title="Password" description="Last changed 28 days ago" action="Change password" /><ActionRow icon={<LockKeyhole size={17} />} title="Two-factor authentication" description="Add an extra layer of protection" action="Enable 2FA" /><ActionRow icon={<UserRound size={17} />} title="Team permissions" description="Manage roles and access policies" action="Manage roles" /></div></SettingsCard><SettingsCard icon={<Database size={18} />} eyebrow="Audit trail" title="Recent security activity" description="A record of important changes in your workspace."><div className="space-y-3">{[["Admin signed in", "Today, 9:42 AM", "success"], ["Workspace settings updated", "Yesterday, 4:18 PM", "neutral"], ["New API key created", "Jun 12, 2024", "warning"]].map(([title, date, status]) => <div key={title} className="flex items-center gap-3 rounded-2xl bg-[#f7f3f2] p-3"><StatusDot status={status as "success" | "neutral" | "warning"} /><span className="text-sm font-medium">{title}</span><span className="ml-auto text-xs text-neutral-400">{date}</span></div>)}</div></SettingsCard></>}
        {activeSection === "Integrations" && <SettingsCard icon={<Webhook size={18} />} eyebrow="Connected services" title="Integrations" description="Connect the tools that power your Orderly workspace."><IntegrationRow icon={<Database size={18} />} name="NestJS API" description="Primary order management service" status="Ready to connect" action="Configure" /><IntegrationRow icon={<Webhook size={18} />} name="Webhooks" description="Send order events to external services" status="Not configured" action="Add endpoint" /><IntegrationRow icon={<Zap size={18} />} name="Automation" description="Trigger workflows from order events" status="Coming soon" action="Learn more" /></SettingsCard>}
        <p className="px-1 text-xs leading-5 text-neutral-400">Changes are mocked locally for now. These controls are structured to connect to your NestJS + MySQL administration API.</p>
      </div>
    </div>
  </div></main>
}

function SettingsCard({ icon, eyebrow, title, description, children }: { icon: React.ReactNode; eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-3xl bg-white p-6 shadow-[0_12px_40px_rgba(28,27,27,.05)] sm:p-8"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#f7f3f2] text-neutral-700">{icon}</span><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-neutral-500">{description}</p></div></div><div className="mt-7">{children}</div></section> }
function Field({ label, value, suffix, disabled }: { label: string; value: string; suffix?: string; disabled?: boolean }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-neutral-700">{label}</span><div className="flex h-11 items-center rounded-xl border border-black/10 bg-white px-3 text-sm"><span className="text-neutral-400">{suffix}</span><input className="min-w-0 flex-1 bg-transparent outline-none disabled:text-neutral-400" defaultValue={value} disabled={disabled} /></div></label> }
function SelectField({ label, value, options }: { label: string; value: string; options: string[] }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-neutral-700">{label}</span><div className="relative"><select className="h-11 w-full appearance-none rounded-xl border border-black/10 bg-white px-3 pr-10 text-sm outline-none focus:border-black" defaultValue={value}>{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 text-neutral-400" size={16} /></div></label> }
function ToggleRow({ label, description, enabled, onChange, locked }: { label: string; description: string; enabled: boolean; onChange?: () => void; locked?: boolean }) { return <div className="flex items-center gap-4 border-b border-black/5 py-4 last:border-0"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs leading-5 text-neutral-500">{description}</p></div><button type="button" onClick={onChange} disabled={locked} aria-pressed={enabled} aria-label={`${label}: ${enabled ? "on" : "off"}`} className={`relative h-6 w-11 shrink-0 rounded-full p-1 transition ${enabled ? "bg-black" : "bg-neutral-200"} disabled:cursor-not-allowed disabled:opacity-70`}><span className={`block size-4 rounded-full bg-white transition-transform ${enabled ? "translate-x-5" : "translate-x-0"}`} /></button></div> }
function ActionRow({ icon, title, description, action }: { icon: React.ReactNode; title: string; description: string; action: string }) { return <div className="flex items-center gap-3 border-b border-black/5 py-4 last:border-0"><span className="grid size-9 place-items-center rounded-xl bg-[#f7f3f2] text-neutral-600">{icon}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-neutral-500">{description}</p></div><button className="button-secondary h-9 px-3 text-xs">{action}</button></div> }
function IntegrationRow({ icon, name, description, status, action }: { icon: React.ReactNode; name: string; description: string; status: string; action: string }) { return <div className="flex flex-col gap-4 border-b border-black/5 py-5 last:border-0 sm:flex-row sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-black text-white">{icon}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{name}</p><p className="mt-1 text-xs text-neutral-500">{description}</p></div><span className="text-xs text-neutral-400">{status}</span><button className="button-secondary h-9 px-3 text-xs">{action}</button></div> }
function SectionIcon({ item }: { item: string }) { const Icon = item === "Workspace" ? Store : item === "Profile" ? UserRound : item === "Orders" ? Store : item === "Notifications" ? Bell : item === "Security" ? ShieldCheck : Webhook; return <Icon size={14} /> }
